language: node_js
node_js:
- stable
addons:
  sonarcloud:
    organization: buscapadel
    token:
      secure: Tz+hlwwDVxEsvkcMxid3uUVD5PzNJt2T9rG+2FotW2AQutzWEL/clKYTAoczwMwgvLZqvo/y+gQ59UCj3dOQtFKx/u/wb2ooA5AE0EQly/zaPe/MhcQd3i/FYSk3AmR7JHL13ZqU3ZkcQu1AyFYs4Gwd0xYfoRdv7BOo8G7u7i0z5X5ddHUqA9UioWjqetWzvdmPBq9sdRbxOnXNRAsAG0hP6ihyg0kSwu0UUqstD5cAWCM0DcSzR0L+SyW6ipQ/oXs6Vy/mr+sLRNsPQ/cjT9m+XVHzQj81/dyFe/+B2ge25Z3StHi7OyGWqjKQY75NpCFeF48n3eLg3zSf52PxHaO9jGly9XlOcz57HPAmj5PxulXz/6CX7P3+3SunUKEyOPGkXEcZP2aBBM5wz5k/OFp/7Q0HdmgjxpLqxuJy9MnwSdgJfzqkxwvsHpaAfojeWZTjKRK7t1U0vuXSezMDbVcP6aBbMUlOSTnvWLzL1kY4ZNwUVEqTOfBmDY2TOuCg6CxhQpENqOhk9IBlCklhh0MZ7KhosI16Y96PbF+rA2+7uIhPhjMruIlS1U0jgztUheSH2NY4FDKRyzdlbAvAnjOvlDGocQYxd2j9p6netH+o5cy8LjZ/bDYTcbK4zRjkC1wO3akS6VTj7liZqC90z1v8hQW/zNWnjoFws5VQ46M=
script:
- sonar-scanner
env:
  global:
    secure: Tz+hlwwDVxEsvkcMxid3uUVD5PzNJt2T9rG+2FotW2AQutzWEL/clKYTAoczwMwgvLZqvo/y+gQ59UCj3dOQtFKx/u/wb2ooA5AE0EQly/zaPe/MhcQd3i/FYSk3AmR7JHL13ZqU3ZkcQu1AyFYs4Gwd0xYfoRdv7BOo8G7u7i0z5X5ddHUqA9UioWjqetWzvdmPBq9sdRbxOnXNRAsAG0hP6ihyg0kSwu0UUqstD5cAWCM0DcSzR0L+SyW6ipQ/oXs6Vy/mr+sLRNsPQ/cjT9m+XVHzQj81/dyFe/+B2ge25Z3StHi7OyGWqjKQY75NpCFeF48n3eLg3zSf52PxHaO9jGly9XlOcz57HPAmj5PxulXz/6CX7P3+3SunUKEyOPGkXEcZP2aBBM5wz5k/OFp/7Q0HdmgjxpLqxuJy9MnwSdgJfzqkxwvsHpaAfojeWZTjKRK7t1U0vuXSezMDbVcP6aBbMUlOSTnvWLzL1kY4ZNwUVEqTOfBmDY2TOuCg6CxhQpENqOhk9IBlCklhh0MZ7KhosI16Y96PbF+rA2+7uIhPhjMruIlS1U0jgztUheSH2NY4FDKRyzdlbAvAnjOvlDGocQYxd2j9p6netH+o5cy8LjZ/bDYTcbK4zRjkC1wO3akS6VTj7liZqC90z1v8hQW/zNWnjoFws5VQ46M=
