CREATE TABLE ligas (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  nombre VARCHAR(100) DEFAULT NULL ,
  numJugadores int(3) DEFAULT NULL
);


ALTER TABLE partidos ADD COLUMN fkIdLiga int(11) DEFAULT NULL;

ALTER TABLE partidos ADD   CONSTRAINT `partidos_LIGA` FOREIGN KEY (`fkIdLiga`) REFERENCES `liga` (`id`) ON UPDATE CASCADE;